import Navbar from "@/components/Navbar";
import AppSidebar from "@/components/AppSidebar";
import { useEffect, useState } from "react";
import {
  getHistory,
  HistoryRecord,
  getFuture,
  FuturePrediction,
} from "@/services/api";
import { useAppState } from "@/context/AppContext";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  ResponsiveContainer,
  CartesianGrid,
  Tooltip,
} from "recharts";
import {
  TrendingUp,
  TrendingDown,
  Minus,
  Download,
  Zap,
  Lightbulb,
  ChevronDown,
  FileText,
  Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { toast } from "sonner";

// ── PDF Export ───────────────────────────────────────────────────────────────

async function exportPDF(history: HistoryRecord[], userName: string) {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF();
  const now = new Date().toLocaleString();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(30, 58, 138); // Primary blue
  doc.text("Mental Health Assessment Report", 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Patient: ${userName}`, 14, 32);
  doc.text(`Generated: ${now}`, 14, 38);
  doc.text("System: Digital Twin Mental Health Platform", 14, 44);

  // Divider
  doc.setDrawColor(30, 58, 138);
  doc.setLineWidth(0.5);
  doc.line(14, 48, 196, 48);

  // Summary section
  if (history.length > 0) {
    const latest = history[0];
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("Latest Assessment Summary", 14, 58);

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const summaryY = 66;
    doc.text(`Date: ${latest.date}`, 14, summaryY);
    doc.text(`Risk Score: ${latest.risk_score}%`, 14, summaryY + 6);
    doc.text(
      `Anxiety Probability: ${latest.anxiety_probability}%`,
      14,
      summaryY + 12
    );
    doc.text(
      `Depression Probability: ${latest.depression_probability}%`,
      14,
      summaryY + 18
    );
    doc.text(`Cognitive State: ${latest.cognitive_state}`, 14, summaryY + 24);
    doc.text(
      `Neural Symmetry: ${latest.neural_symmetry}%`,
      14,
      summaryY + 30
    );

    // Risk level badge
    const riskLevel =
      latest.risk_score <= 25
        ? "LOW"
        : latest.risk_score <= 50
          ? "MODERATE"
          : latest.risk_score <= 75
            ? "ELEVATED"
            : "HIGH";

    doc.text(`Overall Risk Level: ${riskLevel}`, 120, summaryY);
  }

  // Historical Data Table
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text("Historical Assessment Data", 14, 104);

  const tableData = history.slice(0, 20).map((row) => [
    row.date,
    `${row.risk_score}%`,
    `${row.anxiety_probability}%`,
    `${row.depression_probability}%`,
    `${row.sleep}/100`,
    `${row.stress}/100`,
    row.cognitive_state,
  ]);

  autoTable(doc, {
    startY: 110,
    head: [
      [
        "Date",
        "Risk",
        "Anxiety",
        "Depression",
        "Sleep",
        "Stress",
        "State",
      ],
    ],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255 },
    alternateRowStyles: { fillColor: [240, 245, 255] },
    theme: "grid",
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This report is generated by the Digital Twin Mental Health Platform for informational purposes.",
    14,
    pageHeight - 20
  );
  doc.text(
    "It is NOT a medical diagnosis. Please consult a qualified healthcare professional.",
    14,
    pageHeight - 15
  );

  doc.save(`mental_health_report_${Date.now()}.pdf`);
}

// ── Component ────────────────────────────────────────────────────────────────

const History = () => {
  const { userId, user } = useAppState();
  const [history, setHistory] = useState<HistoryRecord[]>([]);
  const [future, setFuture] = useState<FuturePrediction | null>(null);
  const [showAll, setShowAll] = useState(false);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (!userId) return;
    setLoading(true);
    Promise.all([getHistory(userId), getFuture(userId)])
      .then(([h, f]) => {
        setHistory(h);
        setFuture(f);
      })
      .finally(() => setLoading(false));
  }, [userId]);

  const displayedHistory = showAll ? history : history.slice(0, 5);

  // Build trajectory chart data from real history
  const trajectoryData = [...history]
    .reverse() // Chronological order for chart
    .map((row) => ({
      date: row.date.replace(/, \d{4}$/, ""), // "Nov 5" format
      value: row.risk_score,
    }));

  // Build future projection chart data
  const futureChartData =
    future && future.dates.length > 0
      ? future.dates.map((d, i) => ({
          date: d,
          value: future.risk_values[i],
          projected: true,
        }))
      : [];

  // Combined chart data
  const combinedChart = [
    ...trajectoryData.slice(-10).map((d) => ({ ...d, projected: false })),
    ...futureChartData,
  ];

  const TrendIcon = ({ trend }: { trend: string }) => {
    if (trend === "up")
      return <TrendingUp className="w-4 h-4 text-destructive" />;
    if (trend === "down")
      return <TrendingDown className="w-4 h-4 text-sanctuary-green" />;
    return <Minus className="w-4 h-4 text-muted-foreground" />;
  };

  const handleExportPDF = async () => {
    if (history.length === 0) {
      toast.error("No data to export");
      return;
    }
    setExporting(true);
    try {
      await exportPDF(history, user?.name || "Unknown");
      toast.success("PDF Report Generated", {
        description: "Your mental health report has been downloaded.",
      });
    } catch (e) {
      toast.error("PDF export failed");
      console.error(e);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="flex">
        <AppSidebar />
        <main className="flex-1 p-8 max-w-[1100px] mx-auto">
          <div className="flex items-start justify-between mb-8">
            <div>
              <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-2">
                Cognitive Overview
              </h1>
              <p className="text-muted-foreground max-w-lg">
                A real-time reflection of your neural harmony and emotional
                equilibrium.{" "}
                {history.length > 0 && (
                  <span className="text-primary font-semibold">
                    {history.length} records tracked.
                  </span>
                )}
              </p>
            </div>
            <div className="flex gap-3">
              <Button
                variant="outline"
                className="gap-2"
                onClick={handleExportPDF}
                disabled={exporting || history.length === 0}
              >
                {exporting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <FileText className="w-4 h-4" />
                )}
                Export PDF
              </Button>
              <Link to="/dashboard">
                <Button className="gap-2 rounded-lg">
                  <Zap className="w-4 h-4" /> Recalibrate Twin
                </Button>
              </Link>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-8">
            {/* Historical Trajectory — now uses real data */}
            <div className="md:col-span-3 bg-card rounded-2xl border border-border p-6">
              <div className="flex items-center justify-between mb-1">
                <div>
                  <h3 className="text-lg font-bold text-foreground">
                    Historical Trajectory
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    Risk score over time
                    {futureChartData.length > 0 && " (+ projected)"}
                  </p>
                </div>
              </div>
              <div className="h-[260px] mt-4">
                {loading ? (
                  <div className="flex items-center justify-center h-full">
                    <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
                  </div>
                ) : combinedChart.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={combinedChart}>
                      <CartesianGrid
                        strokeDasharray="3 3"
                        vertical={false}
                        stroke="hsl(214, 20%, 92%)"
                      />
                      <XAxis
                        dataKey="date"
                        tick={{ fontSize: 10, fill: "hsl(215, 14%, 50%)" }}
                        axisLine={false}
                        tickLine={false}
                        interval="preserveStartEnd"
                      />
                      <YAxis
                        tick={{ fontSize: 11, fill: "hsl(215, 14%, 50%)" }}
                        axisLine={false}
                        tickLine={false}
                        domain={[0, 100]}
                        tickFormatter={(v) => `${v}%`}
                      />
                      <Tooltip
                        formatter={(val: number) => [`${val}%`, "Risk Score"]}
                        labelStyle={{ fontSize: 12 }}
                      />
                      <Line
                        type="monotone"
                        dataKey="value"
                        stroke="hsl(211, 100%, 40%)"
                        strokeWidth={2.5}
                        dot={false}
                        strokeDasharray={(entry: any) =>
                          entry?.projected ? "5 5" : "0"
                        }
                      />
                    </LineChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="flex items-center justify-center h-full text-muted-foreground text-sm">
                    No history data yet. Run an assessment to start tracking.
                  </div>
                )}
              </div>
            </div>

            {/* Future Projection — now data-driven */}
            <div className="md:col-span-2 flex flex-col gap-6">
              <div className="bg-gradient-to-br from-sanctuary-teal-dark to-primary rounded-2xl p-6 text-primary-foreground">
                <h3 className="text-lg font-bold mb-2">Future Projection</h3>
                <p className="text-sm text-primary-foreground/80 mb-5">
                  {future?.trend_direction === "improving"
                    ? "Trends suggest your mental health is improving. Keep up the positive habits!"
                    : future?.trend_direction === "worsening"
                      ? "Risk trajectory is trending upward. Consider increasing protective activities."
                      : "Predictive analysis shows a stable risk trajectory based on your recent patterns."}
                </p>
                {future && (
                  <div className="space-y-4">
                    <div>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="text-primary-foreground/80">
                          Focus Probability
                        </span>
                        <span className="font-bold">
                          {future.focus_probability}%
                        </span>
                      </div>
                      <div className="w-full bg-primary-foreground/20 rounded-full h-2">
                        <div
                          className="bg-primary-foreground rounded-full h-2 transition-all duration-500"
                          style={{
                            width: `${future.focus_probability}%`,
                          }}
                        />
                      </div>
                    </div>
                    <div>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="text-primary-foreground/80">
                          Stress Resistance
                        </span>
                        <span className="font-bold">
                          {future.stress_resistance}%
                        </span>
                      </div>
                      <div className="w-full bg-primary-foreground/20 rounded-full h-2">
                        <div
                          className="bg-sanctuary-green rounded-full h-2 transition-all duration-500"
                          style={{
                            width: `${future.stress_resistance}%`,
                          }}
                        />
                      </div>
                    </div>
                    {future.risk_values.length > 0 && (
                      <div className="mt-2 pt-3 border-t border-primary-foreground/20">
                        <p className="text-xs text-primary-foreground/60 uppercase tracking-wider mb-2">
                          Projected Risk
                        </p>
                        <div className="flex gap-3">
                          {future.dates.map((d, i) => (
                            <div key={d} className="text-center flex-1">
                              <p className="text-lg font-bold">
                                {future.risk_values[i]}%
                              </p>
                              <p className="text-xs text-primary-foreground/60">
                                {d}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Weekly Wisdom */}
              <div className="bg-card rounded-2xl border border-border p-5 flex items-start gap-3">
                <div className="w-9 h-9 rounded-full bg-sanctuary-green-light flex items-center justify-center shrink-0">
                  <Lightbulb className="w-4 h-4 text-sanctuary-green" />
                </div>
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                    Weekly Wisdom
                  </p>
                  <p className="text-sm text-foreground">
                    {history.length >= 5
                      ? `Over your last ${Math.min(history.length, 10)} sessions, your average risk score is ${Math.round(history.slice(0, 10).reduce((s, r) => s + r.risk_score, 0) / Math.min(history.length, 10))}%.`
                      : "Complete more assessments to unlock personalized weekly insights."}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* History Table */}
          <div className="mt-2">
            <h2 className="text-2xl font-extrabold text-foreground mb-1">
              Digital Twin History
            </h2>
            <p className="text-sm text-muted-foreground mb-6">
              Archived states and historical biometric snapshots
            </p>

            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
              </div>
            ) : history.length === 0 ? (
              <div className="bg-card rounded-2xl border border-border p-12 text-center">
                <p className="text-muted-foreground">
                  No history yet. Go to the Dashboard to run your first
                  assessment.
                </p>
              </div>
            ) : (
              <div className="bg-card rounded-2xl border border-border overflow-hidden">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-border">
                      {[
                        "Snapshot ID",
                        "Cognitive State",
                        "Neural Symmetry",
                        "Date Recorded",
                        "Risk",
                        "Trend",
                      ].map((h) => (
                        <th
                          key={h}
                          className="text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider px-6 py-4"
                        >
                          {h}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {displayedHistory.map((row) => (
                      <tr
                        key={row.id}
                        className="border-b border-border last:border-0 hover:bg-muted/30 transition-colors"
                      >
                        <td className="px-6 py-4 text-sm font-semibold text-foreground">
                          {row.id}
                        </td>
                        <td className="px-6 py-4 text-sm text-foreground flex items-center gap-2">
                          <span
                            className={`w-2 h-2 rounded-full ${
                              row.risk_score > 50
                                ? "bg-sanctuary-orange"
                                : "bg-sanctuary-green"
                            }`}
                          />
                          {row.cognitive_state}
                        </td>
                        <td className="px-6 py-4 text-sm text-muted-foreground">
                          {row.neural_symmetry}% Stability
                        </td>
                        <td className="px-6 py-4 text-sm text-muted-foreground">
                          {row.date}
                        </td>
                        <td className="px-6 py-4 text-sm font-semibold text-foreground">
                          {row.risk_score}%
                        </td>
                        <td className="px-6 py-4">
                          <TrendIcon trend={row.trend} />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {history.length > 5 && (
              <button
                onClick={() => setShowAll(!showAll)}
                className="flex items-center gap-1 mx-auto mt-4 text-sm text-muted-foreground hover:text-foreground"
              >
                {showAll ? "Show Less" : `Show All ${history.length} Records`}{" "}
                <ChevronDown
                  className={`w-4 h-4 transition-transform ${showAll ? "rotate-180" : ""}`}
                />
              </button>
            )}
          </div>
        </main>
      </div>
    </div>
  );
};

export default History;
